apiVersion: apiextensions.k8s.io/v1beta1 # 一旦beta版を利用
kind: CustomResourceDefinition
metadata:
  name: samples.stable.example.com
spec:
  group: stable.example.com # MUST
  versions: # MUST
  - name: v1alpha
    served: true
    storage: true
  scope: Namespaced # MUST
  names: # MUST
    kind: Sample
    plural: samples
    singular: sample
    shortNames: ["sp"]
